@startuml
object Application
object Menu
object Database
object Calendar
object Workout
object Stats
object User
object WorkoutProgram
object Exercise
object ExerciseCreator
object Settings
object TextUI

Application *-- Database
Application *-- Menu
Application *-- User

Menu *-- WorkoutProgram
Menu *-- Settings
Menu *-- Calendar
Menu *-- Workout
Menu *-- Stats

Workout *-- WorkoutProgram

WorkoutProgram *-- Exercise
WorkoutProgram *-- ExerciseCreator

@enduml